name: 10min cron job
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - name: My GraphQL Query
      run: curl -X POST 'https://srivani-strapi-backend.onrender.com/graphql/'
